### ISSUE TITLE
no animation with MMM-Page-Selector

### ISSUE THREAD

**Issue by GattoJohnny** [Tomadelostacos/MMM-LesJoiesDuCode#3]
Hello,

I've been using the MMM-Page-Selector for quite a while. Recently I came across your nice module and gave it a try. Unfortunately only a static image is shown instead of the whole animation. Without MMM-Page-Selector your module works fine.
Do you know of any incompatibility issues between them?

I'd be glad to provide you with any logs or config details, whatever you need to get this work.

Thanks ahead,
Gyorgy

**Comment by GattoJohnny** [comment]
ping

**Comment by Tomadelostacos** [comment]
Hello ! Sorry for inconvenience, didn't work on this Github account for quite a while.. Do you still have this issue ? Didn't check with the MMM-Page-Selector when i wrote the module ! 

I'll give it a try when i'll finish my mirror, thanks for the feedback though. 
Thomas

**Comment by GattoJohnny** [comment]
Hi,

Thanks for getting back to the issue. No, I gave it up years ago. Maybe it's a node.js problem, maybe something else, I do not mind it anymore. My mirror works as charm without receiving any updates and I'm fine with that.
Your module is nice, though.

Take care, György

**Comment by Tomadelostacos** [comment]
Thanks a lot ! 

Take care
